### ISSUE TITLE
Multiple Gif Upload

### ISSUE THREAD

**Issue by riveramj** [hacklanta/gifbot#2]
I've got lots of gifs from a different gif bot. Is there a way to store multiple?

`.gifbot nailed-it url1, url2, url3, url4` maybe?

**Comment by Shadowfiend** [comment]
That almost seems easier to handle via a one-time import on the command line or something.

**Comment by farmdawgnation** [comment]
Any chance your gif bot happens to have a rocket ship? The parts from the rocket ship could be reconfigured together to form a gif pipeline amirite?

**Comment by farmdawgnation** [comment]
In all seriousness, I think the answer here is to use an import script. If you can get me JSON, I can get you gifs in our Slack instance. :)

**Comment by riveramj** [comment]
I'll get you the json. And interestingly enough, the other gif bot attached to a rocket ship...
